### PR TITLE
Update netgen to build on macOS for Apple Silicon

### PR DESCRIPTION
**Pull request by oursland**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This branch bumps up the version of netgen to 6.2.2302 which includes support for building on Apple Silicon.  Separate directives for the deployment target and build machine are specified to support building on and for both x86_65 and arm64 macOS.

A migration to support python3.11 is included to support the most recent build.

Closes #45

### CODE REVIEW

**Comment by jakirkham** [comment]
Added a note in the OP to close out the macOS ARM migrator PR (since this does that work already)

**Comment by mikemhenry** [comment]
I think you wanted to import `netgen` and not `pymbar` 🙃

**Comment by looooo** [comment]
To build for osx-arm you need to add this line and render:
https://github.com/conda-forge/pivy-feedstock/blob/main/conda-forge.yml#L3

**Comment by looooo** [comment]
Just in case you don't know. For freecad Netgen is bundled with smesh:
https://github.com/trelau/SMESH/blob/master/.gitmodules#L1

**Comment by oursland** [comment]
> Just in case you don't know. For freecad Netgen is bundled with smesh: https://github.com/trelau/SMESH/blob/master/.gitmodules#L1

I see.  I had issues on some builds in loading the FEM examples and figured it was due to the CMake not finding netgen.  I have confirmed that without netgen the builds operate correctly.

**Pull request closed without merging**
